### ISSUE TITLE
update the Software controller - TODO #1

### ISSUE THREAD

**Issue by davasorus** [davasorus/TEPSClientInstallServiceAgent#29]
this will allow a simple endpoint to check connectivity, also it could check the logfile for the agent and update for the text "ERROR" 
 counting up from the bottom of the file 50 or so lines

- [ ] Change GetString() to GetHealthCheck()
- [ ] should be able to iterate through the logging files for the agent AND the updater to see if there are any errors.
- [ ] Ideally the API will return a HTTP code of 200 for the general message, BUT I want you to use the tupleList with the tupleData to return if there are errors in the logging. Response Code should be 400 Bad Request, message should be the message from the log

**Comment by davasorus** [comment]
The code for the TODO is in the Dev Branch, I'll be merging it soon. The comment has a little more information but let me know if you have any questions @flyingguerrilla @DeWolfe6

**Comment by davasorus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TEPS Client Install Agent](https://trello.com/c/kwpEDsIJ/949-teps-client-install-agent)
